### ISSUE TITLE
RestEasy集成Swagger失败

### ISSUE THREAD

**Issue by fsolsh** [kimmking/kk#1]
First：Spring Bean初始化报错
![image](https://user-images.githubusercontent.com/33198812/35850415-b7b1f7fe-0b5f-11e8-804e-5e7b1251e449.png)

**Comment by fsolsh** [comment]
Second：看到scan默认也是true，在配置文件中删除
![image](https://user-images.githubusercontent.com/33198812/35850946-74e816ea-0b61-11e8-918b-cf83371db165.png)

**Comment by fsolsh** [comment]
Third：访问swagger页面
![image](https://user-images.githubusercontent.com/33198812/35851016-a0764890-0b61-11e8-8718-67ef9dcf8d66.png)

**Comment by fsolsh** [comment]
![image](https://user-images.githubusercontent.com/33198812/35851650-98da0f2a-0b63-11e8-93de-19513ee90465.png)
![image](https://user-images.githubusercontent.com/33198812/35851671-aa81095e-0b63-11e8-983a-9bebfd74ab52.png)

**Comment by fsolsh** [comment]
访问RestEasy服务，是正常的。
****问题是Swagger并没有document RestEasy服务****
请抽时间帮忙看一下这个问题，谢谢！

**Comment by kimmking** [comment]
swagger里引用dubboService的路径不对
